server:
  port: 8080
logging.pattern.console: "%d{&quot;yyyy-MM-dd'T'HH:mm:ss.SSSZ&quot;} %highlight(%-5level) [%thread] rid=[%X{rid}] %logger{36} - %msg %rEx{30}%n"
pitchfork:
  forwarders:
    haystack:
      kinesis:
        enabled: false
        region-name: "us-west-1"
        stream-name: "proto-spans"
        endpoint-config-type: REGION
        authentication-type: DEFAULT
      kafka:
        enabled: true
        bootstrap-servers: kafka-service:9092
        topic: proto-spans
    logging:
      enabled: false
      log-full-span: false
    zipkin:
      enabled: false
      endpoint: http://localhost:9411/api/v2/spans
      max-inflight-requests: 256
      write-timeout-millis: 10000
      compression-enabled: true
