name: Build

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build:
    name: Build and Unit Tests
    runs-on: ubuntu-latest
    env:
      JAVA_DOWNLOAD_CHECKSUM: 6c06853332585ab58834d9e8a02774b388e6e062ef6c4084b4f058c67f2e81b5
    steps:
      - uses: actions/checkout@v1
      - run: |
          wget "https://github.com/AdoptOpenJDK/openjdk14-binaries/releases/download/jdk-14%2B36/OpenJDK14U-jdk_x64_linux_hotspot_14_36.tar.gz"
          echo "${JAVA_DOWNLOAD_CHECKSUM}  OpenJDK14U-jdk_x64_linux_hotspot_14_36.tar.gz"  | sha256sum -c
      - name: Set up JDK 14
        uses: actions/setup-java@v1
        with:
          java-version: 14
          jdkFile: ./OpenJDK14U-jdk_x64_linux_hotspot_14_36.tar.gz
      - name: Build with Maven
        run: ./mvnw verify
